language: erlang

sudo: required

services:
  - docker

# install latest rebar3 because the one travis provids doesn't support cover_export_name option
before_install:
  - |
    git clone https://github.com/erlang/rebar3.git
    pushd .
    cd rebar3
    ./bootstrap
    sudo mv rebar3 /usr/local/bin/
    popd
  - sudo docker info

notifications:
  email: false

otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  - make
  - make xref
  - make edoc
  - |
    OTP_VSN=`erl -noshell -eval 'io:format(erlang:system_info(otp_release)), halt(0)'`
    if [ $OTP_VSN -eq 21 ]; then
      make dialyze
    fi
  - export KAFKA_VERSION=2.4  && make testbed && make eunit
  - export KAFKA_VERSION=1.1  && make testbed && make eunit
  - export KAFKA_VERSION=0.11 && make testbed && make eunit
  - export KAFKA_VERSION=0.10 && make testbed && make eunit
  - export KAFKA_VERSION=0.9  && make testbed && export KPRO_TEST_KAFKA_09=1 && make eunit
  - make cover

